"""Brand theme for every generated PDF/PNG artifact (visuals.py).

The repo default is the PRESS brand — the warm-paper editorial system
Nate's site, ghostwriter cards, and devlog covers share (canonical
sources: ghostwriter `diagram.css` `.card.press` + the devlog image
style guide, 2026-07-18). Because this is a public repo, the theme is
**local-overridable**: point ``LOCAL_FITNESS_BRAND_FILE`` at a JSON
file (``data/brand.json`` is the natural gitignored home) and its keys
deep-merge over the default — swap one color or replace the whole
identity without touching tracked code. A missing or broken brand file
must never break a render: any load error logs a warning and falls back
to the default theme.

PRESS rules the default encodes (see the style guide's "never do"):
flat paper, ink rules for structure, no rounded corners / shadows /
gradients, and ONE signature accent used sparingly — tones and verdicts
are carried typographically (ink / dim / italic), with the accent
reserved for critical/missed items.
"""
from __future__ import annotations

# >>> press:tokens v0.2.0 sha256:6ac33fdf62c0 GENERATED by @natjswenson/press, do not edit
import copy
import json
import logging
import os
from pathlib import Path

_LOG = logging.getLogger(__name__)

_BRAND_FILE_ENV = "LOCAL_FITNESS_BRAND_FILE"

DEFAULT_THEME: dict = {
    "name": "press",
    "colors": {
        # Warm cream. Flat — never gradiented, never textured.
        "paper": "#F5F0E6",
        # One step down from paper, for a panel that must separate from the
        # page without a border. Still flat.
        "paper_surface": "#ECE5D6",
        # Two steps down. The deepest paper tone; below this, use an ink rule
        # instead.
        "paper_elevated": "#E4DCCA",
        # Near-black. Text, headlines, and every structural rule.
        "ink": "#181510",
        # Muted secondary text; the serif commentary voice's color.
        "dim": "#6E675C",
        # THE one loud color. Spent once or twice per document, never as
        # decoration.
        "accent": "#E8501F",
        # Rules are ink, named separately so an override can soften them
        # without touching text color.
        "rule": "#181510",
        # Mid ink step: a second series, a stacked-bar segment, a bar track.
        "ink_mid": "#4A423A",
        # Decorative only — a faint element inside an illustration. Never body
        # text, never a headline.
        "ink_faint": "#8A8272",
    },
    "fonts": {
        # Display/structure voice, set 800-900 with tight tracking by the CSS.
        "display_stack": "-apple-system, BlinkMacSystemFont, 'Segoe UI', Arial, sans-serif",
        # Commentary voice: serif italics for standfirsts and captions.
        "serif_stack": "'New York', ui-serif, Georgia, 'Times New Roman', serif",
        # Data voice: labels, dates, tables, provenance.
        "mono_stack": "ui-monospace, 'SF Mono', Menlo, monospace",
        # Point at a real TTF to load an authentic mono face via @font-face.
        "mono_file": None,
    },
    "identity": {
        # Typographic stamp (rotated square, accent border + initials).
        "stamp": "NS",
        # Masthead eyebrow, tracked caps: "{brand_line} · MORNING BRIEF · date".
        "brand_line": "LOCAL FITNESS",
        # Right-aligned dim byline in the masthead.
        "byline": "linkedin.com/in/natejswenson",
    },
}


def _deep_merge(base: dict, override: dict) -> dict:
    """Recursively merge ``override`` into a copy of ``base``.

    Non-dict values replace; unknown keys are kept, so a brand file written
    against a newer default still loads against an older one.
    """
    out = copy.deepcopy(base)
    for key, value in override.items():
        if isinstance(value, dict) and isinstance(out.get(key), dict):
            out[key] = _deep_merge(out[key], value)
        else:
            out[key] = copy.deepcopy(value)
    return out


def load_theme() -> dict:
    """The active theme: ``DEFAULT_THEME`` merged with ``LOCAL_FITNESS_BRAND_FILE``.

    Read per render rather than cached, so editing the brand file takes effect
    on the next render without restarting anything. A missing or broken brand
    file must never break a render, so any load error falls back to the
    default.
    """
    theme = copy.deepcopy(DEFAULT_THEME)
    brand_file = os.environ.get(_BRAND_FILE_ENV)
    if brand_file:
        try:
            override = json.loads(Path(brand_file).expanduser().read_text(encoding="utf-8"))
            if isinstance(override, dict):
                theme = _deep_merge(theme, override)
            else:
                _LOG.warning(
                    "brand file %s is not a JSON object — using default theme", brand_file)
        except (OSError, ValueError):
            _LOG.warning(
                "could not load brand file %s — using default theme",
                brand_file, exc_info=True)
    mono_file = theme.get("fonts", {}).get("mono_file")
    if mono_file:
        theme["fonts"]["mono_file"] = str(Path(mono_file).expanduser())
    return theme
# <<< press:tokens
