import { useState, lazy, Suspense, type ComponentType } from 'react'
import { useSearchParams } from 'react-router-dom'
import { cn } from '@/lib/utils'
import { StatCard } from './StatCard'
import { TakeawayCard } from './TakeawayCard'
import { Card } from './Card'

/**
 * Preview route for the uxpolish tool.
 *
 * Mounts the original component plus any ``<Name>.v{1,2,3}.tsx`` variants
 * that exist on disk (generated by ``tools/uxpolish/suggest.py``) and lets
 * you flip between them with a tab bar. Fixture props are hardcoded per
 * component so the rendered preview is realistic without backend round-trips.
 *
 * Variants are discovered at build time via ``import.meta.glob``, scoped to
 * the ``.v[1-3].tsx`` suffix only — including the unsuffixed originals in
 * the glob would collide with the static imports used by the main app and
 * silently break the production bundle (Vite warns about this; we hit it).
 */

type FixtureFn = () => Record<string, unknown>

const FIXTURES: Record<string, FixtureFn> = {
  StatCard: () => ({
    label: 'Resting HR',
    value: '52',
    unit: 'bpm',
    delta: '−2 vs baseline',
    deltaTone: 'good',
    sub: '14-day trend',
    sparkline: Array.from({ length: 14 }, (_, i) => ({
      date: `2026-04-${String(14 + i).padStart(2, '0')}`,
      value: 54 - Math.sin(i / 2) * 2,
    })),
  }),
  TakeawayCard: () => ({
    takeaway: {
      headline: 'Fitness has dropped a third this month',
      summary:
        "Your CTL slid from 16.3 down to 10.7 in 30 days — that's 35% lower. Three to four weeks of consistent runs, easy to moderate, will move it back.",
      tone: 'critical',
      metric: { metric: 'ctl', days: 60 },
      details:
        "CTL tracks your fitness over the past six weeks. Yours has fallen sharply over the last 30 days — three weeks of low volume showing up in the numbers. To reverse, aim for 4 sessions per week at easy/moderate effort. Today's run was step one. Don't let step two wait another six days.",
    },
    onAsk: () => alert('Ask handler stub'),
  }),
  Card: () => ({ children: 'A simple card.' }),
}

// Statically-known originals so the "Original" tab works without any glob
// collision with the rest of the app.
const ORIGINALS: Record<string, ComponentType<Record<string, unknown>>> = {
  StatCard: StatCard as ComponentType<Record<string, unknown>>,
  TakeawayCard: TakeawayCard as ComponentType<Record<string, unknown>>,
  Card: Card as ComponentType<Record<string, unknown>>,
}

// Variants only — narrow glob avoids polluting the production bundle's
// chunk graph with the rest of the app.
const VARIANT_MODULES = import.meta.glob<Record<string, unknown>>('./*.v[1-3].tsx')

const VARIANT_LABELS = ['Original', 'Variant 1', 'Variant 2', 'Variant 3']

export function VariantHost() {
  const [params] = useSearchParams()
  const componentName = params.get('component') ?? ''
  const [active, setActive] = useState(0)

  if (!componentName) {
    return (
      <div className="p-8 text-muted">
        <p className="text-sm">
          Add <code className="text-text">?component=&lt;Name&gt;</code> to the URL.
        </p>
        <p className="text-sm mt-2">
          E.g. <code className="text-text">/__uxpolish?component=StatCard</code>
        </p>
        <p className="text-sm mt-4">
          Supported: {Object.keys(FIXTURES).join(', ')}
        </p>
      </div>
    )
  }

  const fixtureFn = FIXTURES[componentName]
  const Original = ORIGINALS[componentName]
  if (!fixtureFn || !Original) {
    return (
      <div className="p-8 text-bad">
        <p>No fixture/original registered for "{componentName}".</p>
        <p className="text-sm text-muted mt-2">
          Add it to FIXTURES + ORIGINALS in <code>VariantHost.tsx</code>.
        </p>
      </div>
    )
  }

  // Probe variant availability via the module map keys.
  const variantPaths = [1, 2, 3].map((n) => `./${componentName}.v${n}.tsx`)
  const variantAvailable = variantPaths.map((p) => Boolean(VARIANT_MODULES[p]))
  const available = [true, ...variantAvailable]

  // Build a lazy component for the active tab. Tab 0 uses the static
  // original; tabs 1-3 lazy-load the variant chunk.
  let LazyComponent: ComponentType<Record<string, unknown>> | null = null
  if (active === 0) {
    LazyComponent = Original
  } else {
    const path = variantPaths[active - 1]
    const loader = VARIANT_MODULES[path]
    if (loader) {
      LazyComponent = lazy(() =>
        loader().then((mod) => ({
          default: mod[componentName] as ComponentType<Record<string, unknown>>,
        })),
      )
    }
  }

  const props = fixtureFn()

  return (
    <div className="min-h-screen bg-bg text-text">
      {/* Sticky tab bar so it stays reachable while scrolling. */}
      <div className="sticky top-0 z-10 bg-bg/85 backdrop-blur border-b border-border">
        <div className="px-4 py-2 flex items-center gap-2 overflow-x-auto">
          <span className="text-xs text-muted shrink-0 pr-1">{componentName}</span>
          {VARIANT_LABELS.map((label, i) => (
            <button
              key={i}
              onClick={() => setActive(i)}
              disabled={!available[i]}
              className={cn(
                'shrink-0 px-3 py-1 rounded-full text-[12px] transition-colors',
                active === i
                  ? 'bg-surface text-text border border-border'
                  : available[i]
                    ? 'text-muted hover:text-text border border-transparent hover:bg-surface/60'
                    : 'text-faint border border-transparent cursor-not-allowed opacity-50',
              )}
              title={available[i] ? '' : 'Not generated — run tools/uxpolish/suggest.py'}
            >
              {label}
            </button>
          ))}
        </div>
      </div>

      {/* Preview frame — sized to the iPhone width Nate cares about most. */}
      <div className="px-4 py-6">
        <div className="mx-auto w-full max-w-[420px]">
          <Suspense fallback={<div className="text-sm text-muted">Loading…</div>}>
            {LazyComponent ? (
              <LazyComponent {...props} />
            ) : (
              <div className="text-sm text-muted">No variant at {variantPaths[active - 1]}</div>
            )}
          </Suspense>
        </div>
      </div>
    </div>
  )
}
